import pickle
from .intake import YelpReviewReader

class Predict(object):
    def __init__(self, model_pkl_path):
        self.model_pkl_path = model_pkl_path

    def predict(self, sentence):
        if sentence == "" or type(sentence) != str:
            raise ValueError("Sentence invalid")

        try:
            pkl_file = open(self.model_pkl_path, "rb")
            model = pickle.load(pkl_file)
        except:
            raise ValueError("Pickled data invalid. Use model generated by Model.create_model")
        tokens = [YelpReviewReader.tokenize(sentence)]
        prediction = model.predict(tokens)[0]
        sentiment = "negative" if prediction == 0 else "positive"
        print("This review is {}".format(sentiment))
